### ISSUE TITLE
AssetNotFoundException: Models/Archer/archer.j3o

### ISSUE THREAD

**Issue by stephengold** [capdevon/Archer-Game-Template#2]
Trying to execute the application, I get an error:
```text
Nov 09, 2020 2:43:42 PM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.2-stable
 * Branch: HEAD
 * Git Hash: 8291d61
 * Build Date: 2019-07-13
Nov 09, 2020 2:43:43 PM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
INFO: LWJGL 3.2.1 build 12 context running on thread main
 * Graphics Adapter: GLFW 3.3.0 X11 GLX EGL clock_gettime evdev shared
Nov 09, 2020 2:43:44 PM com.jme3.renderer.opengl.GLRenderer loadCapabilitiesCommon
INFO: OpenGL Renderer Information
 * Vendor: NVIDIA Corporation
 * Renderer: GeForce GT 545/PCIe/SSE2
 * OpenGL Version: 4.6.0 NVIDIA 390.138
 * GLSL Version: 4.60 NVIDIA
 * Profile: Compatibility
Nov 09, 2020 2:43:44 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio Renderer Information
 * Device: OpenAL Soft
 * Vendor: OpenAL Community
 * Renderer: OpenAL Soft
 * Version: 1.1 ALSOFT 1.19.1
 * Supported channels: 64
 * ALC extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFT_device_clock ALC_SOFT_HRTF ALC_SOFT_loopback ALC_SOFT_output_limiter ALC_SOFT_pause_device
 * AL extensions: AL_EXT_ALAW AL_EXT_BFORMAT AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_BFORMAT AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_EXT_SOURCE_RADIUS AL_EXT_STEREO_ANGLES AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFTX_events AL_SOFTX_filter_gain_ex AL_SOFT_gain_clamp_ex AL_SOFT_loop_points AL_SOFTX_map_buffer AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length AL_SOFT_source_resampler AL_SOFT_source_spatialize
Nov 09, 2020 2:43:44 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio effect extension version: 1.0
Nov 09, 2020 2:43:44 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio max auxiliary sends: 2
Bullet-Native: Initializing java classes
Nov 09, 2020 2:43:44 PM com.jme3.scene.plugins.ogre.SceneMaterialLoader startElement
WARNING: Cannot locate material file: Scenes/ManyLights/Scene.material
Nov 09, 2020 2:43:45 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[main,5,main]
com.jme3.asset.AssetNotFoundException: Models/Archer/archer.j3o
	at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:370)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:416)
	at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:420)
	at mygame.PlayerManager.setupPlayer(PlayerManager.java:46)
	at mygame.PlayerManager.simpleInit(PlayerManager.java:35)
	at com.capdevon.engine.SimpleAppState.initialize(SimpleAppState.java:71)
	at com.jme3.app.state.AppStateManager.initializePending(AppStateManager.java:251)
	at com.jme3.app.state.AppStateManager.update(AppStateManager.java:281)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:236)
	at com.jme3.system.lwjgl.LwjglWindow.runLoop(LwjglWindow.java:499)
	at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:581)
	at com.jme3.system.lwjgl.LwjglWindow.create(LwjglWindow.java:423)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:463)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:424)
	at com.jme3.app.SimpleApplication.start(SimpleApplication.java:125)
	at mygame.Main.main(Main.java:44)
```

Looks like `AnimDefs` sets `MODEL` to "Models/Archer/archer.j3o" but the asset is actually located at "Models/gltf2/Archer/archer.j3o".

**Comment by capdevon** [comment]
You are absolutely right, I fixed the problem and updated the README.txt file with the explanation of the game keys. Let me know if there are any other bugs. As soon as I have some free time, let's discuss the feedback you suggested on the forum. Thanks ;)

**Comment by capdevon** [comment]
this issue should be resolved, let me know if everything works

**Comment by stephengold** [comment]
The issue is resolved.
